### ISSUE TITLE
ROS plugin doesn't compile

### ISSUE THREAD

**Issue by alexanderkoller** [dialogos-project/dialogos#179]
I'm trying to put together the 2.1.1 release, and the ROS plugin doesn't compile. Perhaps the dependency to DialogOS has the wrong version?

```
koller@hilbert ~/D/w/d/dialogos-plugin-ros> ./gradlew run

> Task :compileJava FAILED
/Users/koller/Documents/workspace/dialogos/dialogos-plugin-ros/src/main/java/app/dialogos/ros/plugin/ROSPluginSettings.java:96: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
1 actionable task: 1 executed
```

**Comment by alexanderkoller** [comment]
@timobaumann Could you look into this?

**Comment by alexanderkoller** [comment]
Hang on, maybe I can fix it with the 2.1.1 release.

**Comment by alexanderkoller** [comment]
Yep, will work in 2.1.1.

**Comment by timobaumann** [comment]
yes, sorry. I forgot to update the dependency in the repo. fixed there now as well.
